[package]
name = "decaf377"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
hex = "0.4"
num-bigint = "0.4"
once_cell = "1.8"
tracing = "0.1"
tracing-subscriber = "0.2"
anyhow = "1.0"
ark-relations = "0.3"
ark-r1cs-std = {version = "0.3", optional=true }
ark-std = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-serialize = "0.3"
ark-bls12-377 = "0.3"
ark-ed-on-bls12-377 = { version = "0.3", features = ["r1cs"] }
ark-groth16 = { version = "0.3", optional=true }
ark-snark = { version = "0.3", optional=true }
zeroize = "1.4"

[features]
default = []
r1cs = ["ark-r1cs-std", "ark-groth16", "ark-snark"]

[dev-dependencies]
proptest = "1"
criterion = { version = "0.3", features=["html_reports"] }
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand_chacha = "0.3"

[[test]]
name = "groth16_gadgets"
required-features = ["r1cs"]

[[bench]]
name = "sqrt"
harness = false
