[package]
name = "decaf377"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
hex = "0.4"
num-bigint = "0.4"
once_cell = "1.8"
tracing = "0.1"
tracing-subscriber = "0.2"
ark-relations = "0.3"
ark-r1cs-std = "0.3"
ark-std = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-serialize = "0.3"
ark-ed-on-bls12-377 = { version = "0.3", features = ["r1cs"] }
zeroize = "1.4"

[dev-dependencies]
proptest = "1"
